### PR TITLE
Fix for failing fossology tests

### PR DESCRIPTION
**Pull request by radoslawc**
Fix for https://github.com/nephio-project/sig-release/issues/43

### CODE REVIEW

**Comment by johnbelamaric** [comment]
@radoslawc the UI-based rebase isn't working for me, with some EasyCLA complaint. Can you try rebasing?

**Comment by arora-sagar** [comment]
@radoslawc @johnbelamaric can we merge this branch? As it fixes the failing license test.

**Comment by radoslawc** [comment]
@arora-sagar @johnbelamaric Sorry for late reply, missed that one in notifications. I rebase it either,  it was made from branch on api repo and it's protected so I cannot update it. I'll close this one and open proper one from fork.
/close

**Pull request closed without merging**
